version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=f1
      - DOCKER_INFLUXDB_INIT_PASSWORD=f1telemetry123
      - DOCKER_INFLUXDB_INIT_ORG=f1
      - DOCKER_INFLUXDB_INIT_BUCKET=f1_telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=f1_telemetry_token